name: lily-assistant - test and publish

on: push

jobs:
  test-and-push:
    name: Unit Tests - working branch
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Display Python version
        run: python -V

      - name: Install dependencies
        working-directory: .
        run: make install

      - name: Launch Linter
        working-directory: .
        run: make lint

      - name: Launch tests
        working-directory: .
        run: make test_all

      # if launched from master branch, then build and publish to PyPI
      - name: Build and publish
        if: github.ref == 'refs/heads/master'
        working-directory: .
        run: |
          python setup.py bdist_wheel
          twine upload -u __token__ -p ${{ secrets.PYPI_LILY_ASSISTANT_API_TOKEN }} dist/*.whl
